# Generated by Django 4.1.5 on 2023-01-29 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='attendance.question'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='presentation',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='attendance.presentation'),
        ),
    ]
