# Generated by Django 4.1.5 on 2023-01-29 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_answer_question_alter_presentation_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.presentation'),
        ),
    ]
