# Generated by Django 4.1.5 on 2023-01-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_session_join_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='join_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
